# Generated by Django 4.2.6 on 2023-10-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_customuser_display_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('-starts_at', '-ends_at')},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='ends_at',
            field=models.DateTimeField(default='2000-01-01T00:00:00+05:30'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='starts_at',
            field=models.DateTimeField(default='2000-01-01T00:00:00+05:30'),
        ),
    ]
